### ISSUE TITLE
Feature Request: Finaliser Method

### ISSUE THREAD

**Issue by liam-veitch** [noxdafox/pebble#101]
The initialiser method is useful for calling at process creation. Would be great if there was an equivalent finalizer method to be called just prior to closing a worker process.

An example use case - I have a worker processes which must operate within their own directory (I call os.chdir). The folders are generated using a random string. The finalizer method would be used to delete these folders.

I use Python 2.7 - not everyone has the luxury of moving to higher versions due to interfacing with (old) commercial software!!

**Comment by noxdafox** [comment]
It is not possible to guarantee that a "finalizer" function is executed. For example, if the process is terminated upon timeout or `future.cancel()` request, it is likely that the function won't be called. The same would apply in case of pool termination as well as other cases (process OOM etc.).

This is why the pool does not provide a mirror for the initializer function.

You can easily implement the functionality yourself via [`atexit.register`](https://docs.python.org/2.7/library/atexit.html#atexit.register) or [`sys.exitfunc`](https://docs.python.org/2.7/library/sys.html#sys.exitfunc). Keep in mind that none of these methods provide guarantees your cleanup function will be executed.

Example:

```python
def initializer():
    path = tempfile.mkdtemp('/tmp/')
    os.chdir(path)
    atexit.register(cleanup, path)

def cleanup(path):
    os.rmdir(path)

pool = pebble.Pool(initializer=initializer)

...

```

**Comment by noxdafox** [comment]
Closing this issue due to lack of response. Please re-open if you require further clarifications.

**Comment by noxdafox** [comment]
Hello,

please avoid necroposting. Although relevant to the topic, it's hard to track these discussions. Open a new issue next time. It also helps understanding how desirable a feature is.

The reason why `atexit` registered callbacks are not called is not due to `os._exit()`. The [code path you are looking at](https://github.com/noxdafox/pebble/blob/master/pebble/pool/process.py#L441) gets executed only in case the pipe gets abruptly closed which usually happens when your main loop crashes. Processes, are usually terminated via `Process.terminate` which issue a `SIGTERM` signal. Python, by default, does not handle such signal and the process exits without executing your registered functions.

To prove it, you can try this code snippet:
```python
import signal

from pebble import ProcessPool


def initializer():
    print('initializing')
    signal.signal(signal.SIGTERM, cleanup)


def cleanup(*_, **__):
    print('cleanup')


def do_nothing():
    pass


if __name__ == "__main__":
    pool = ProcessPool(initializer=initializer, max_workers=1)
    pool.submit(do_nothing, None)
    pool.close()
    pool.join()
```   

The reason why a "finalizer" or "deinitializer" function is not provided in `pebble` is because there is no reliable way to guarantee a callback is executed at process termination.

There are several ways a process can quit which cannot be handled:
 * Your function uses a library which calls `os._exit` under the hood.
 * Your function becomes unresponsive upon termination request. A `SIGKILL` signal will handle such cases upon futures cancellations or timeout.
 * The OS forcibly terminates your process due to OOM.

The only safe way to handle cleanup after a process has ended is within the main loop. This can simply be achieved via installing a `SIGCHLD` handler for example. 
```python
import os
import signal

from pebble import ProcessPool


def initializer():
    print(f'Process {os.getpid()} initializing...')


def cleanup(_signum, _frame):
    pid, status = os.waitpid(-1, os.WNOHANG)
    print(f'Child process {pid} exited with status {status}')


def do_nothing():
    pass


if __name__ == "__main__":
    signal.signal(signal.SIGCHLD, cleanup)
    pool = ProcessPool(initializer=initializer, max_workers=1)
    pool.submit(do_nothing, None)
    pool.close()
    pool.join()
```

Issue with this strategy is the main loop will not have the worker process context. This in practice limits the actions which can be taken. You can indeed perform filesystem cleanup routines if, for example, you use the process `PID` as filesystem path. Yet you cannot perform more advanced cleanups such as closing sockets and whatnot. This is the reason I did not add this functionality in `pebble`: it's limited and can easily lead to confusion.

**Comment by noxdafox** [comment]
I see, there is indeed a chance in which registered functions via `atexit` might not executed. 

This was most likely due to make sure the pool quits quickly in case of a crash in the main loop but this should be ensured nowadays by the workers stopping logic.

I removed the `os._exit` call and replaced with regular termination of the process in case of the channel gets closed from the main loop as this is assumed to be a rather normal situation.

I will make a release soon(ish) once the stress tests have been run.

**Comment by charettes** [comment]
Thanks @noxdafox, appreciated!

Looks like it caused some of the tests to hang though, unsure what caused it as I can't reproduce locally.

**Comment by charettes** [comment]
Actually it looks like `test/test_pebble.py::TestWaitForThreads::test_waitforthreads_single` is hanging for me after a few tries.

**Comment by noxdafox** [comment]
Yes, I am looking into the matter. There was a reason why I was forcefully exiting on `EOFError` but since I do not have all the platforms available I can solely rely on github actions nowadays.

Since the hang happens on Windows, I will try to get my hands on a Windows box.
