### ISSUE TITLE
The timeout argument of ProcessPool().submit() is inconsistent with ThreadPool().submit()

### ISSUE THREAD

**Issue by victoryhb** [noxdafox/pebble#110]
Hi, thanks for the awesome library, which I am trying out and like a lot.
One inconsistency I have found in the API, however, is that the positional `timeout` argument in ProcessPool().submit() is inconsistent with ThreadPool().submit(). 
Compare:
`futures = [pool.submit(func, None, i) for i in range(10)]`
with 
`futures = [pool.submit(func, i) for i in range(10)]`
The ProcessPool version is harder to use since it is easy to forget to add the `timeout` argument before the function argument `i`, making it error prone when swapping different types of pools. It is also arguably uglier. 
As a comparison, with the built-in concurrent.futures library, 
`tasks = [executor.submit(func, i) for i in range(10)]`
would have worked for both ThreadPoolExecutor and ProcessPoolExecutor, which I think is consistent and elegant.
I wonder if there is any possibility of addressing this issue?
Thanks!

Victor

**Comment by noxdafox** [comment]
Hello,

the `pool.submit` has been designed to be compatible with `concurrent.future.Executor.submit` for the sake of supporting `asyncio.loop.run_in_executor` API.

The `concurrent.future.Executor.submit` API passes arguments and keyword arguments straight to the submitted function making positional arguments the only way to provide submission specific parameters.

This is evident in the [function signature](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.submit) `Executor.submit(fn, /, *args, **kwargs)` note the `/` marking positional only parameters. 

It would not be possible, in fact, to provide a signature such as `ProcessPool.submit(fn, *args, timeout=None, **kwargs)` as this would prevent submitting functions with a `timeout` keyword arguments such as [`requests.get`](https://requests.readthedocs.io/en/latest/user/quickstart/#timeouts). Moreover, the above API would not allow to submit jobs within `asyncio.loop.run_in_executor` as it would not be possible to submit them altogether with a timeout.

If you want to use `ThreadPool` and `ProcessPool` interchangeably and you don't care about the timeout functionality then you can simply use a class wrapper for it.

```python
class Pool:
    def __init__(pool: [pebble.ProcessPool, pebble.ThreadPool]):
        self._pool = pool

    def submit(fn, *args, **kwargs):
         if isinstance(self._pool, pebble.ProcessPool):
            self._pool.submit(fn, None, *args, **kwargs)

pool = Pool(pebble.ProcessPool())
futures = [pool.submit(func, i) for i in range(10)]
```

Keep in mind that `ThreadPool` and `ProcessPool` do not provide the same behaviour. Futures returned by `ProcessPool` can be cancelled and can timeout. In such cases, the underlying process will be interrupted avoiding to consume extra resources. The same is not true for `ThreadPool` due to the fact that running threads cannot be interrupted. Hence, you need to keep this aspect in mind when exchanging one pool with the other.

**Comment by victoryhb** [comment]
Thanks a lot for the enlightening remarks on the rationale behind such a design decision. 
I see that the positional `timeout` argument was added mainly to be compatible with libs like asyncio.
Coming from concurrent.futures, however, I was surprised by the subtle incompatibity in the API. I personallly would have preferred full compatibility by adding a special keyword argument like `pebble_timeout`, which also avoids the somewhat redundant use of `None` in many cases.

**Comment by noxdafox** [comment]
Goal with pebble is not to be `concurrent.futures` compatible. Only in recent versions I adopted a somewhat similar API to make it more friendly and also to re-use the `Future` class.

I find the `Executor` API pretty simplistic and I don't think that adding a custom namespace `_pebble_specific_timeout` is the correct solution. 

I will reinstate the [`schedule`](https://pebble.readthedocs.io/en/latest/#pebble.ProcessPool.schedule) API as the recommended function for submitting jobs to the Pools and leave the `submit` for mere compatibility with `asyncio.loop.run_in_executor`.
