### ISSUE TITLE
Workers using 100% CPU not getting killed after timeout

### ISSUE THREAD

**Issue by dmbaggett** [noxdafox/pebble#129]
I have a server with a ProcessPool:

            self.pool = pebble.ProcessPool(max_workers=max_workers, max_tasks=max_tasks)

In this case, `max_workers=4` and `max_tasks=32`.

I then schedule tasks with `self.pool.schedule(..., timeout=4.0)`.

Very rarely (after thousands of tasks) a subprocess gets stuck forever using 100% CPU. Here's an example ps output when this happens -- in this case both PID 1333707 and PID 2619592 have been stuck for 6 days:

```
ubuntu    710081       1  1 Mar08 ?        02:58:16   python document_server.py -P 1500 --log-to-file
ubuntu    710473  710081  0 Mar08 ?        00:00:02     /home/ubuntu/install/linux/3.12/bin/python -c from multiprocessing.resource_tracker import main;main(8)
ubuntu    710540  710081  0 Mar08 ?        00:00:48     /home/ubuntu/install/linux/3.12/bin/python -c from multiprocessing.forkserver import main; main(12, 13, ['__main__'], **{'sys_path': ['/home/ubuntu/inky-main/ink-drop/addinserver', '/home/ubuntu/cpython-3.12/lib/python312.zip', '/home/ubuntu/cpython-3.12/lib/python3.12', '/home/ubuntu/cpython-3.12/lib/python3.12/lib-dynload', '/home/ubuntu/install/linux/3.12/lib/python3.12/site-packages']})
ubuntu   1333707  710540 99 Mar13 ?        6-07:04:19       /home/ubuntu/install/linux/3.12/bin/python -c from multiprocessing.forkserver import main; main(12, 13, ['__main__'], **{'sys_path': ['/home/ubuntu/inky-main/ink-drop/addinserver', '/home/ubuntu/cpython-3.12/lib/python312.zip', '/home/ubuntu/cpython-3.12/lib/python3.12', '/home/ubuntu/cpython-3.12/lib/python3.12/lib-dynload', '/home/ubuntu/install/linux/3.12/lib/python3.12/site-packages']})
ubuntu   2619592  710540 99 Mar13 ?        6-02:20:52       /home/ubuntu/install/linux/3.12/bin/python -c from multiprocessing.forkserver import main; main(12, 13, ['__main__'], **{'sys_path': ['/home/ubuntu/inky-main/ink-drop/addinserver', '/home/ubuntu/cpython-3.12/lib/python312.zip', '/home/ubuntu/cpython-3.12/lib/python3.12', '/home/ubuntu/cpython-3.12/lib/python3.12/lib-dynload', '/home/ubuntu/install/linux/3.12/lib/python3.12/site-packages']})
ubuntu   1213584  710540 18 19:27 ?        00:00:00       /home/ubuntu/install/linux/3.12/bin/python -c from multiprocessing.forkserver import main; main(12, 13, ['__main__'], **{'sys_path': ['/home/ubuntu/inky-main/ink-drop/addinserver', '/home/ubuntu/cpython-3.12/lib/python312.zip', '/home/ubuntu/cpython-3.12/lib/python3.12', '/home/ubuntu/cpython-3.12/lib/python3.12/lib-dynload', '/home/ubuntu/install/linux/3.12/lib/python3.12/site-packages']})
ubuntu   1213780  710540 22 19:27 ?        00:00:00       /home/ubuntu/install/linux/3.12/bin/python -c from multiprocessing.forkserver import main; main(12, 13, ['__main__'], **{'sys_path': ['/home/ubuntu/inky-main/ink-drop/addinserver', '/home/ubuntu/cpython-3.12/lib/python312.zip', '/home/ubuntu/cpython-3.12/lib/python3.12', '/home/ubuntu/cpython-3.12/lib/python3.12/lib-dynload', '/home/ubuntu/install/linux/3.12/lib/python3.12/site-packages']})
```

Any suggestions on how to debug what's getting stuck here? And is there some belt-and-suspenders method I can use to just manually kill any workers that have been running at 100% CPU for more than some period of time? From reading https://github.com/noxdafox/pebble/issues/97 it seems that running an external process harvester will only make things worse.

**Comment by noxdafox** [comment]
Hello,

these issues are a bit tricky to debug as usually this happens to be a long running service and the core issue might have happened long in the past.

You can look at few things.

1. Check in your kernel logs if any OOM killer has happened. When a Linux server goes OOM, lots of weird things can happen. Usually the OOM killer intervenes and kill some of the offending processes but in the meanwhile something might have failed and crashed. 
2. Check in the service log if any of the Pool threads have crashed. I suspect that in the above case the thread responsible for detecting problematic workers (timeouts etc...) might have crashed. An OOM might be, for example, the reason for a thread to crash.
3. If you cannot see anything from logs (because of log rotation for example), check that all 3 maintenance threads are still alive. Each pool has 3 maintenance threads. If one is missing it means it has crashed. You can use the command `ps -T -p <pid>` to list the threads of a process.

**Comment by dmbaggett** [comment]
Thanks @noxdafox . Regarding #1, it's definitely not an OOM kill. I think we can also rule out #2. If/when it happens again, I will use your ps command in #3.

**Comment by noxdafox** [comment]
If your main process is complex, it might have several running threads within which will make it hard to distinguish which thread is which.

In such case, you might want to use `gdb` with Python extensions and inspect each thread yourself. You should be able to see the 3 main loops up and running. 

These are the loops you are looking for:
 * https://github.com/noxdafox/pebble/blob/master/pebble/pool/process.py#L156
 * https://github.com/noxdafox/pebble/blob/master/pebble/pool/process.py#L176
 * https://github.com/noxdafox/pebble/blob/master/pebble/pool/process.py#L187
In particular, the `pool_manager_loop` is the one responsible for detecting timing out workers.

**Comment by dmbaggett** [comment]
I believe I have a single thread, but I will verify.

**Comment by dmbaggett** [comment]
Under Ubuntu, is there a scenario where the OS could have sent a signal to the child process and put it into a bad state, preventing the parent from killing it? That seems like a likely scenario to me.

**Comment by noxdafox** [comment]
Pebble sends 2 signals when termination is needed:
 * `SIGTERM` is considered the standard mean to require termination of a process. It lets the process perform any needed cleanup. This signal can be ignored. Equivalent of bash command `$ kill -15 <pid>`.
 * `SIGKILL` is considered the mean to enforce the termination of a process. It cannot be ignored as the OS itself terminates the process when the above signal is issued. Equivalent of bash command `$ kill -9 <pid>`.

Pebble sends first `SIGTERM` to the worker process to make sure it can properly clean up. After few seconds, if the process is still alive, it sends `SIGKILL`. Hence, there is no way the worker process itself can survive.

What is more likely to be happening, is that above logic is not triggering in Pebble. This usually happens when the thread responsible for such is either stuck or exited unexpectedly.

**Comment by dmbaggett** [comment]
If that logic isn't triggering, are you saying would that be due to a bug in Pebble, or my own code? If it could Pebble, I'm up for adding some logging to Pebble itself to try to catch this scenario if you could suggest generally where in the code this happens.

**Comment by dmbaggett** [comment]
Nevermind, I see you gave me pointers to code in process.py above. I will investigate there.

**Comment by noxdafox** [comment]
This is not an issue of Pebble until proven otherwise. The fact that the above mentioned logic *might* not be triggering it's usually a strong indicator the thread loop crashed.

These cases are very rare and usually suggest there is a problem with OS: running out of memory, file descriptors or other critical resources.

If you application would suffer, for example, of a resource leak (memory, file descriptors, ...) it would show only over time and affect any component of the service.

**Comment by dmbaggett** [comment]
Actually it looks like I maybe have been passing a timeout value of 0.0 in rare cases... which could explain why these tasks were never killed. I'll keep an eye on it but I think you can close this.

**Comment by noxdafox** [comment]
A timeout of `0` is equivalent to setting timeout to `None`, it basically means no timeout at all.

Therefore it works as expected. Closing this issue.
