### ISSUE TITLE
map function is extremely slow, seems to be executing sequentially

### ISSUE THREAD

**Issue by ahill187** [noxdafox/pebble#133]
# Description

When using the `map` function, it is significantly slower than the `multiprocessing.Pool.map` function or the `multiprocessing.Pool.imap` function. For example, a task that takes 14 seconds on `multiprocessing.Pool.map` or `multiprocessing.Pool.imap` is taking 48 seconds on `pebble.ProcessPool.map`. It seems that despite using 18 processes, they are running one at a time, or at most two at a time. When I switch from `spawn` to `fork` this seems to improve, although it is still taking 18 seconds.

# Platform / Version

Linux
Ubuntu 22.04
20 CPUs
Python 3.10.12

**Comment by noxdafox** [comment]
Hello,

difficult to assess where the problem is without an example which reproduces the issue. Moreover, you are most likely making the wrong comparisons.

[`multiprocessing.Pool.map`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool.map) expands the whole iterable before scheduling it to its workers. This means that if your collection is large, it will be expanded all in memory. It is faster to do so but at the cost of generating a fair bit of memory pressure. [`pebble.ProcessPool.map`](https://pebble.readthedocs.io/en/latest/#pebble.ProcessPool.map) iterates over the collection instead, slower but safer when dealing with large datasets.

Moreover, both the `map` and `imap` split the given collections into large chunks before sending them to the workers. Pebble primitives have been built to mimic `concurrent.futures.Executor` APIs. [`concurrent.futures.ProcessPoolExecutor.map`] sets a `chunksize` of 1 as `pebble.ProcessPool` does.

If we compare the three pools with the following script:
```python
import time
import concurrent
import multiprocessing

import pebble


array = list(range(100000))


def function(argument):
    return argument


print("multiprocessing.Pool")
start = time.time()
with multiprocessing.Pool() as pool:
    result = pool.map(function, array)
print(f"Took {time.time() - start} seconds")

print("concurrent.futures.ProcessPoolExecutor")
start = time.time()
with concurrent.futures.ProcessPoolExecutor() as pool:
    future = pool.map(function, array)
print(f"Took {time.time() - start} seconds")

print("pebble.ProcessPool")
start = time.time()
with pebble.ProcessPool() as pool:
    future = pool.map(function, array)
print(f"Took {time.time() - start} seconds")

```

We see that `pebble.ProcessPool` compares to `concurrent.futures.ProcessPoolExecutor` in terms of performance:
```
$ python3 issue_133.py 
multiprocessing.Pool
Took 0.023804426193237305 seconds
concurrent.futures.ProcessPoolExecutor
Took 4.969228506088257 seconds
pebble.ProcessPool
Took 4.8503735065460205 seconds
```

A much better comparison would be to use `imap` instead of `map`. This is yet incorrect as both `concurrent.futures.ProcessPoolExecutor` and `pebble.ProcessPool.map` support the chaining of multiple iterators when `imap` does not.
Moreover, setting an equal `chunksize` for all pools level the game quite a bit.

```python
import time
import concurrent
import multiprocessing

import pebble


array = list(range(100000))


def function(argument):
    return argument


print("multiprocessing.Pool")
start = time.time()
with multiprocessing.Pool() as pool:
    result = pool.imap(function, array, chunksize=100)
    list(result)  # imap is lazy so we need to force the results out
print(f"Took {time.time() - start} seconds")

print("concurrent.futures.ProcessPoolExecutor")
start = time.time()
with concurrent.futures.ProcessPoolExecutor() as pool:
    future = pool.map(function, array, chunksize=100)
print(f"Took {time.time() - start} seconds")

print("pebble.ProcessPool")
start = time.time()
with pebble.ProcessPool() as pool:
    future = pool.map(function, array, chunksize=100)
print(f"Took {time.time() - start} seconds")
```

Which yields:
```
$ python3 issue_133.py 
multiprocessing.Pool
Took 0.04171919822692871 seconds
concurrent.futures.ProcessPoolExecutor
Took 0.08044910430908203 seconds
pebble.ProcessPool
Took 0.24255609512329102 seconds
```

In here, we see `pebble.ProcessPool` performing worse than the other two. The explanation is simple, in order to detect timing out, cancelled or faulty tasks, Pebble's pool incurs an extra IPC cost caused by the fact that the workers need to label which tasks they pick up, otherwise the main loop would not be able to identify which worker is processing the problematic task.

Pebble is designed to allow developers to handle problematic computations which is something traditional implementations do not support. The goal is not to beat performance of already existing solutions.
In order to tackle corner cases, we need to pay a performance tradeoff.

When using `pebble.ProcessPool.map` for fast computing of large collections the suggestion is to use a large enough `chunksize` to avoid being penalized too much by the IPC overhead. This is explained as well in the [documentation](https://pebble.readthedocs.io/en/latest/#pools).
