### ISSUE TITLE
Why threadpool doesn't support timeout in schedule and map function

### ISSUE THREAD

**Issue by i3wangyi** [noxdafox/pebble#23]
Hi, 
I really appreciate the contributions of pebble, it supports timeout in multiprocessing. I'm inspired by this answer https://stackoverflow.com/questions/44402085/multiprocessing-map-over-list-killing-processes-that-stall-above-timeout-limi.  I found out threadpool doesn't have this functionality as I test the functionality.

I'd like to know what's the reason behind it and do you have future plan to support it?

**Comment by noxdafox** [comment]
Hello and thanks for using Pebble.

The reason the `ThreadPool` does not support timeouts is because it's not possible to stop a running thread. You can check at [this](https://stackoverflow.com/questions/48540668/where-is-the-memory-leak-how-to-timeout-threads-during-multiprocessing-in-pytho/48545357#48545357) or [this](https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread-in-python?noredirect=1&lq=1) questions for more information in regards.

Only the thread itself can stop executing. The usual approach is using a flag to signal to the thread it needs to interrupt is execution. The thread checks periodically the flag to know whether it can continue or not.
