### ISSUE TITLE
How to save global variables

### ISSUE THREAD

**Issue by aprilahijriyan** [noxdafox/pebble#71]
Hi, btw your module really helped me, but I don't know why I can't save data to a global variable.

**Comment by noxdafox** [comment]
Hello,

could you please better explain what is you are trying to achieve?

**Comment by VakarisZ** [comment]
I have similar issue:
**config.py**
```
class Config:
    some_var = False
```

**pebble_test.py**
```
from config import Config

def function(n):
    print(Config.some_var)

def run_test():
    with ProcessPool() as pool:
        future = pool.map(function, range(1), timeout=10)
        future.result()
```

**main.py**
```
from config import Config
from pebble_test import run_test

Config.some_var = True
run_test()
```

Using python pool, I'd get `True`. Using pebble, I get `False`.

**Comment by noxdafox** [comment]
I just ran your test (add to add an import in `pebble_test.py`) and the result was correct:

```bash
noxdafox@station:/tmp/issue_71$ python main.py 
True

noxdafox@station:/tmp/issue_71$ python3 main.py 
True
```

What OS are you using?

**Comment by VakarisZ** [comment]
I was running windows 10.

**Comment by noxdafox** [comment]
The behaviour you observe is not due to Pebble but it's normal behaviour of processes under Python.

This is documented in the programming guidelines of the `multiprocessing` module:
https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods

```
Global variables

Bear in mind that if code run in a child process tries to access a global variable, then the value it sees (if any) may not be the same as the value in the parent process at the time that Process.start was called.

However, global variables which are just module level constants cause no problems.
```

You cannot use global variables to share information between two processes as they have different memory address spaces.
