### ISSUE TITLE
Unhelpful error message `ProcessExpired('Abnormal termination')`

### ISSUE THREAD

**Issue by ghilesmeddour** [noxdafox/pebble#87]
Hi,

https://github.com/noxdafox/pebble/blob/58d9b4502820bbec95aca648f6af1e50d8965c17/pebble/concurrent/process.py#L157

`ProcessExpired('Abnormal termination')` is not very useful. What do you think about returning the error as is?

**Comment by noxdafox** [comment]
Hello,

The `ProcessExpired` error is raised when the process executing the decorated function dies unexpectedly as [documented](https://pebble.readthedocs.io/en/latest/#pebble.ProcessExpired). From the parent process, there is no more information we can provide as the actual reason for the process to die was most likely internal to the process itself.

You can get hints from the `exitcode` on what might have been the reason for the process to die (external signal, OOM, segfault etc).

Forwarding the `OSError`/`EOFError` as you suggest would only make things more confusing as the User would see something like `OSError("got end of file during message")`. This not only does not provide any better explanation regarding the root cause but misleads the User into thinking there is some messaging issue with their code.
